"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""


#-- setting.py : 장고의 환경설정을 해주는 파일 --> 장고 app이 실행되면 최초로 실행되는 파일

from pathlib import Path

#-- C:원화mysite
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-*ht^vjq_zilok0gb#m%x9wini3!10a^8w=j@po1zg_9)sy2@k0"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [      #-- 여기에 장고 application을 등록해야함
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "mysite.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "mysite.wsgi.application"
#-- 장고에서 제공하는 웹 어플리케이션 서버를 사용한다는 뜻
#-- wsgi: synchronous 동기 = 그냥 줄 서야함
#-- asgi: asynchronous 비동기 = 대리 줄세우고 순서 됐다고 하면 들어가는 방식


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = { #-- database 설정 넣어주기
    "default": {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'poll_db',
        'USER': 'root',
        'PASSWORD': 'kjygoo0924!',
        'HOST': '127.0.0.1',
        'PORT': '3306',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True #-- 국제화 다국어 사용

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/" #-- Static 파일을 사용한다

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field


#--- source venv/bin/activate
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField" #--orm 관련

INSTALLED_APPS = [
    "polls.apps.PollsConfig", #-- 모듈 단위로 되어있어서 polls를 쓰려면 이렇게 추가해줘야한다.
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]